### ISSUE TITLE
Disable line wrap in code blocks

### ISSUE THREAD

**Issue by VovanR** [VovanR/notes#10]
```css
pre {
    overflow: auto;
}

pre code {
    white-space: pre;
    word-wrap: normal;
}
```
